# Generated by Django 4.1.2 on 2022-10-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_app', '0004_regbootmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginbootmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
